insert into category values('grain');
insert into category values('flours');
insert into category values('dry fruits');
insert into category values('vegetables');
insert into category values('fruits');
insert into category values('dairy');
insert into category values('oil & spices');
insert into category values('toiletries');
insert into category values('munchings');
insert into category values('juices & drinks');
insert into category values('bakery');
insert into category values('househod & cleaning');
